### ISSUE TITLE
MongoNetworkError

### ISSUE THREAD

**Issue by ituageorge** [ituageorge/exam-timed-backend-app#3]
MongoNetworkError: connection 1 to 3.211.181.49:27017 closed
    at C:\Users\GEORGE\Desktop\exam-timed-backend-app\node_modules\mongodb\lib\cmap\connection.js:68:15
    at Map.forEach (<anonymous>)
    at TLSSocket.<anonymous> (C:\Users\GEORGE\Desktop\exam-timed-backend-app\node_modules\mongodb\lib\cmap\connection.js:67:20)
    at TLSSocket.emit (events.js:228:7)
    at net.js:664:12
    at TCP.done (_tls_wrap.js:481:7) {
  name: 'MongoNetworkError'
}

**Comment by ituageorge** [comment]
This error has disappeared because it was a network issue

**Comment by Adebolavictor** [comment]
can we have a screen sharing session to resolve this?
let me know when its convenient for you
